package lab_final_valeriaosoriovictorbarbosa;

import javax.swing.JButton;
import static lab_final_valeriaosoriovictorbarbosa.Historia.l;
import static lab_final_valeriaosoriovictorbarbosa.Inicio.desicion;

public class Decision extends javax.swing.JFrame {

    /**
     * Creates new form Decision
     */
    static int sw = 2;
    static int f = (desicion + 1) / 2;
    static int dia = f;

    public Decision() {
        initComponents();
        this.setLocationRelativeTo(null);
        Inicio n = new Inicio();
        Impresor.setText("<html><body>Para ver sus decisiones haga click <br/> en el boton de abajo.<html>");
        nickname.setText(n.nick);
        esconder(siguiente);
    }

    void esconder(JButton j) {
        j.setContentAreaFilled(false);
        j.setFocusPainted(false);
        j.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        imp = new javax.swing.JLabel();
        progresohistoria = new javax.swing.JProgressBar();
        siguiente = new javax.swing.JButton();
        marco = new javax.swing.JLabel();
        nickname = new javax.swing.JLabel();
        Dia = new javax.swing.JLabel();
        Impresor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imp.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jPanel2.add(imp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 250, 90));
        jPanel2.add(progresohistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 160, 20));

        siguiente.setFont(new java.awt.Font("Book Antiqua", 2, 15)); // NOI18N
        siguiente.setText("Ver decisiones");
        siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        jPanel2.add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 130, 30));

        marco.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        marco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/borde2122.png"))); // NOI18N
        jPanel2.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 120, 30));

        nickname.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        nickname.setForeground(new java.awt.Color(255, 255, 255));
        nickname.setText("Nombre");
        jPanel2.add(nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 90, 20));

        Dia.setFont(new java.awt.Font("Old English Text MT", 0, 48)); // NOI18N
        Dia.setText("Dia X");
        jPanel2.add(Dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 230, 120));

        Impresor.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Impresor.setToolTipText("");
        Impresor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(Impresor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 270, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/marx.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 520));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/ada.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 530));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        if (dia != 0) {
            Dia.setText("DIA " + Integer.toString(dia));
            if (sw == 1) {
                Impresor.setText("Ultima decision del dia:");
                sw = 2;
            } else {
                if (dia == 3) {
                    Impresor.setText("Ultima decision del dia:");
                } else {
                    Impresor.setText("Penultima decision del dia:");
                }
                dia = dia - 1;
                sw = 1;
            }
            imp.setText(l.imprimirpila());
        } else {

            Inicio in = new Inicio();
            in.desicion = 0;
            in.orden="";
            in.pr=0;
            in.setVisible(true);
            dispose();
        }
        /*try {
            multi(in.desicion, -1);
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Historia.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_siguienteActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Decision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dia;
    private javax.swing.JLabel Impresor;
    private javax.swing.JLabel imp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel marco;
    public javax.swing.JLabel nickname;
    public static javax.swing.JProgressBar progresohistoria;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
