
package lab_final_valeriaosoriovictorbarbosa;


public class Decision extends javax.swing.JFrame {

    /**
     * Creates new form Decision
     */
    public Decision() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        progresohistoria = new javax.swing.JProgressBar();
        nickname = new javax.swing.JLabel();
        musica = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Dia = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Impresor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(progresohistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 160, 20));

        nickname.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        nickname.setForeground(new java.awt.Color(255, 255, 255));
        nickname.setText("Nombre");
        jPanel2.add(nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 90, 20));

        musica.setBackground(new java.awt.Color(255, 255, 255));
        musica.setForeground(new java.awt.Color(0, 51, 102));
        musica.setText("♫");
        musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicaActionPerformed(evt);
            }
        });
        jPanel2.add(musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("↓");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 50, 30));

        Dia.setFont(new java.awt.Font("Old English Text MT", 0, 48)); // NOI18N
        Dia.setText("Dia X");
        jPanel2.add(Dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 230, 120));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("↑");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 50, 30));

        Impresor.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Impresor.setText("Recuento de las desiciones tomadas    ");
        Impresor.setToolTipText("");
        Impresor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(Impresor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 270, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/marx.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 520));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/ada.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 530));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicaActionPerformed
        // TODO add your handling code here:
        /*JOptionPane.showMessageDialog(null, "Creditos a Uniq en youtube y soundcloud. (Tranqui profe, no tiene copyright)");
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/lab_final_valeriaosoriovictorbarbosa/Art Of Silence_V2.wav"));
        sonido.play();*/
    }//GEN-LAST:event_musicaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio in = new Inicio();
        /*try {
            multi(in.desicion, 1);
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Historia.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Inicio in = new Inicio();
        /*try {
            multi(in.desicion, -1);
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Historia.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Decision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dia;
    private javax.swing.JLabel Impresor;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton musica;
    public javax.swing.JLabel nickname;
    public static javax.swing.JProgressBar progresohistoria;
    // End of variables declaration//GEN-END:variables
}
